### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tartavull** [silvandeleemput/memcnn#1]
Thanks for opensourcing this!

I was reading the code and got confused by this line
https://github.com/silvandeleemput/memcnn/blob/242478b9a55cd3617e8b795a8f6f5653a1ee485d/memcnn/models/revop.py#L96

I thought it wasn't necessary to save inputs or outputs

**Comment by silvandeleemput** [comment]
Hi, I agree that the line looks a bit misleading. There is indeed no need to save the data related to the inputs. 

The actual data associated with the tensors are in fact freed a few lines higher:
https://github.com/silvandeleemput/memcnn/blob/242478b9a55cd3617e8b795a8f6f5653a1ee485d/memcnn/models/revop.py#L88

The function then only stores the reference to the tensors for the backward pass, which is needed at the end of the backward pass to set the input data at the correct place in the computation graph.

I hope my explanation answers your question.

**Comment by tartavull** [comment]
Thanks for taking the time to explain this -- it make sense now.
