### ISSUE TITLE
Fixing the affine coupling 

### ISSUE THREAD

**Issue by silvandeleemput** [silvandeleemput/memcnn#14]
There is a new coupling option added to the ReversibleBlock in the last update of MemCNN.  Currently, only the additive version is properly functioning. There is also the affine coupling, but it does not yet pass the unit tests under models/tests/test_revop.py.

**Comment by robintibor** [comment]
Ok to continue previous discussion: Do you have some method of verifying that the memory on CPU and GPU is properly freed? Just wondering since I don't know what pytorch internally does there, especially if tensor shape and tensor storage are not in sync anymore.

**Comment by silvandeleemput** [comment]
To test if memory is correctly freed, if you have a GPU enabled machine, you can use the unit tests under [memcnn/models/tests/test_memory_saving.py](https://github.com/silvandeleemput/memcnn/blob/b7d1c67966bac1ec9967d5910f3942d803ae81e7/memcnn/models/tests/test_memory_saving.py). It is currently tuned for a GPU with at least 6 GB of memory.

**Comment by robintibor** [comment]
Great. Another question, please redirect me if I should ask it somewhere else, did you consider about having separate `keep_input` and `keep_output` flags?
Normally, I would like to keep x/input on my first layer during forward and keep y/output on my last layer during inverse. However, I do want to remove the y/output on my first layer during inverse and I want to remove the x/input on my last layer during forward.

**Comment by silvandeleemput** [comment]
The affine coupling should now work. It has been covered and passes tests on the dev branch. I will soon merge it with the master branch.
