### ISSUE TITLE
`keep_input=False` is not being tested and seems not to work

### ISSUE THREAD

**Issue by robintibor** [silvandeleemput/memcnn#16]
In https://github.com/silvandeleemput/memcnn/blob/b7d1c67966bac1ec9967d5910f3942d803ae81e7/memcnn/models/tests/test_revop.py
it seems that `keep_input=False` is never being tested.

Due to  https://github.com/silvandeleemput/memcnn/blob/b7d1c67966bac1ec9967d5910f3942d803ae81e7/memcnn/models/tests/test_revop.py#L43 and since `implementation_bwd` always starts at `-1` in the inner loop, `keep_input` remains True in all cases.

This can be solved by having a separate variable for the inner loop e.g.
`this_iter_keep_input = keep_input or (implementation_bwd == -1)`
And using this in the respective lines at
https://github.com/silvandeleemput/memcnn/blob/b7d1c67966bac1ec9967d5910f3942d803ae81e7/memcnn/models/tests/test_revop.py#L50-L51
and
https://github.com/silvandeleemput/memcnn/blob/b7d1c67966bac1ec9967d5910f3942d803ae81e7/memcnn/models/tests/test_revop.py#L69

On my machine, Pytorch 1.1, this makes the test then fail at https://github.com/silvandeleemput/memcnn/blob/b7d1c67966bac1ec9967d5910f3942d803ae81e7/memcnn/models/tests/test_revop.py#L73

Disabling the shape tests does not help, it then just fails later.

Also, further investigation with stacking 2 blocks, shows that somehow the reconstructed x at https://github.com/silvandeleemput/memcnn/blob/b7d1c67966bac1ec9967d5910f3942d803ae81e7/memcnn/models/additive.py#L190

will not correctly be retrieved from
https://github.com/silvandeleemput/memcnn/blob/b7d1c67966bac1ec9967d5910f3942d803ae81e7/memcnn/models/additive.py#L153

Here is a notebook showing some of the failures:
https://gist.github.com/robintibor/2920213008eadd331ef3b69caaea26a8

The outputs like
```
output sum tensor(927.8318)
xout sum tensor(643.7166)
x sum tensor(643.7166)
```

come from adding prints inside the additive.py as:
```python
diff --git a/memcnn/models/additive.py b/memcnn/models/additive.py
index 82347d4..8694db9 100644
--- a/memcnn/models/additive.py
+++ b/memcnn/models/additive.py
@@ -151,6 +151,8 @@ class AdditiveBlockFunction(torch.autograd.Function):

         # retrieve input and output references
         x, output = ctx.saved_tensors
+        import torch as th
+        print("output sum", torch.sum(torch.abs(output)))
         y1, y2 = torch.chunk(output, 2, dim=1)
         y1, y2 = y1.contiguous(), y2.contiguous()

@@ -186,8 +188,10 @@ class AdditiveBlockFunction(torch.autograd.Function):

         # restore input
         xout = torch.cat([x1, x2], dim=1).contiguous()
+        print("xout sum", torch.sum(torch.abs(xout)))
         x.storage().resize_(int(np.prod(xout.shape)))
         x.set_(xout)
+        print("x sum", torch.sum(torch.abs(x)))

         return (grad_input, None, None) + FWgrads + GWgrads
```

Note, the 
```
x sum tensor(927.8318)
output sum tensor(922.7372)
```
in the lower parts of the notebook indicate the retrieved output tensor of the earlier rev block is different from the stored x tensor of the next rev block.

Otherwise there are no further changes to the code of memcnn.

**Comment by silvandeleemput** [comment]
@robintibor thanks for reporting these issues, they should be fixed with the latest commit.
