### ISSUE TITLE
JOSS Review : Community guidelines

### ISSUE THREAD

**Issue by sepandhaghighi** [silvandeleemput/memcnn#19]
1. Move `.github` folder to root
2. Add `CODE_OF_CONDUCT.md` to `.github` folder
3. Move `CONTRIBUTING.rst` to `.github` folder
4. Add `PULL_REQUEST_TEMPLATE.md` to `.github` folder

**Comment by silvandeleemput** [comment]
Performed 1, 2, and 4 as suggested. For 3, I have added a new `CONTRIBUTING.md` to the `.github` folder with a link which always points to the latest version of the contributing section in the documentation. Moving the `CONTRIBUTING.rst` would result in issues with automated documentation building and packaging.

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi I think this can be closed. Do you agree?

Yes, fixed ;-)
