### ISSUE TITLE
Invert function

### ISSUE THREAD

**Issue by tartavull** [silvandeleemput/memcnn#2]
I think it would be really helpful to have an invert method ( I can attempt to write it )
it seems like this repo https://github.com/jhjacobsen/pytorch-i-revnet/issues/4 has code to perform the inverse but not the memory saving.
While your repo is able to perform the memory saving but not the inverse. Having some code capable of doing both would be great.

**Comment by silvandeleemput** [comment]
That seems like a good feature for performing retrospective inference.

The best way would probably be to add a new method to the ReversibleBlock called 'inverse()', this would require writing a new InversedReversibleBlockFunction class, which explicitly computes the inverse and its backward gradients. The relevant code bits can all be found [here](https://github.com/silvandeleemput/memcnn/blob/242478b9a55cd3617e8b795a8f6f5653a1ee485d/memcnn/models/revop.py
)

Alternatively the implicit inverse performed on the backward pass in the ReversibleBlockFunction could be exposed, but this would yield a less clean interface.

I currently don't have the time to do it, but might work on it in the future.

However, if you would like to have a go at it, feel free to do so. 
If you have more questions or run into any issues you can post them in this thread.

**Comment by silvandeleemput** [comment]
Alright, today I implemented the inverse function as an explicit inverse of the ReversibleBlock. 

I have also added an example how to use it to the revop unittest, see:

https://github.com/silvandeleemput/memcnn/blob/dccc2d85ddf6dbcfb194bdf3c3eed9961d1a1356/memcnn/models/tests/test_revop.py#L61-L75

**Comment by tartavull** [comment]
This is just great! Thank you a lot :)
