### ISSUE TITLE
JOSS Review : Add memcnn to Anaconda Cloud

### ISSUE THREAD

**Issue by sepandhaghighi** [silvandeleemput/memcnn#23]
Most of machine learning libraries  are available in `conda` package manager.
You can add your package directly from `PyPI` to `Anaconda Cloud` by using of `skeleton` and `conda-build`.

**Comment by silvandeleemput** [comment]
@sepandhaghighi Hi, thanks for your suggestion. I really like this idea. I have tried to do as you suggested and executed the `skeleton` command to generate a build from `PyPI` directly. However, it appears I am missing an include statement in my `manifest.in`.  This implies I would need to first roll out a new version release to PyPI before I can use this approach. 

It seems to me that your suggested approach is the most simple/desirable, so I would like to stick with it if possible. However, does changing the package version (probably 0.3.3 -> 0.3.4) not conflict with the JOSS review?

**Comment by sepandhaghighi** [comment]
@silvandeleemput 
Hi
You can close this issue at the end.
Wait until the end of the review process, then you should release a new version that include all edits and provide an associated DOI (e.g via `Zenodo`).

**Comment by silvandeleemput** [comment]
I have just released a new version of MemCNN (1.0.0) which contains all the changes from the review and which has a functional Anaconda cloud integration. See: https://anaconda.org/silvandeleemput/memcnn
Also, I have added an anaconda badge in the `readme.rst` and installation instructions for this as well.

I think this issue can be closed as well.

**Comment by sepandhaghighi** [comment]
👍👍 fixed ;-)
