### ISSUE TITLE
Log Determinants

### ISSUE THREAD

**Issue by axium** [silvandeleemput/memcnn#27]
I want to train a generative model. How can I compute log determinant for the Reversible block?

**Comment by silvandeleemput** [comment]
Hi, I am not too familiar with training GANs to go into much detail, but if you want to compute the log determinant can't you just do:

```python
import torch
import memcnn

x = torch.ones(4, 2, 64, 64)
reversible_block = memcnn.ReversibleBlock(...)
log_det = torch.log(torch.det(reversible_block(x)))
```

I wrote this code out of the top of my head and I did not test it. Also, you'll need to provide proper arguments for your data and for the ReversibleBlock. Other than that I think it should work.

**Comment by axium** [comment]
I actually mean log determinants that are typically used in flow based models for example see this [paper](https://d4mucfpksywv.cloudfront.net/research-covers/glow/paper/glow.pdf). Have a look at Table 1.

**Comment by silvandeleemput** [comment]
I see, so you want to compute the log determinants respective to the weights for the reversible block. 

Here is a working example of how to do it:

```python

import torch
import torch.nn as nn
import memcnn

batchsize = 2
channels = 5
conv2d = nn.Conv2d(in_channels=channels, out_channels=channels,
                   kernel_size=(1, 1), padding=0)

class IdentityModule(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x

reversible_block = memcnn.ReversibleBlock(Fm=conv2d, Gm=IdentityModule(), coupling='additive',
                                          keep_input=True, keep_input_inverse=True)

# generate some random input data (batchsize, channels, w, h)
w, h = 8, 8
X = torch.rand(batchsize, channels * 2, w, h)
Y = reversible_block(X)
log_det = w * h * torch.log(torch.abs(torch.det(torch.squeeze(reversible_block.rev_block.Fm.weight))))
print(log_det)

```

**Comment by tychovdo** [comment]
@axium To my understanding, the ReversibleBlock function in memcnn uses additive coupling to create an invertible transformation, which according to section 3.3 in the paper you referenced has a log-determinant of 0. If you would on the other hand use affine coupling, the log-determinant would equal the sum of the log values of the output.

**Comment by silvandeleemput** [comment]
@tychovdo Thank you for your comment. I think you are right which invalidates my earlier approach. I think I have prepared a satisfactory answer this time around, maybe you could double-check its validity?

@axium As you probably already know, there are two couplings supported by the ReversibleBlock the `additive` and the `affine` coupling. As already mentioned, for the `additive` coupling the log-determinant equals 0, because it is a special case of the `affine` coupling with s=1, which gives a log-determinant of 0, according to the formulas in the `glow` paper.

For a ReversibleBlock with the `affine` coupling, the log determinant computation is a bit more complex. Here follows a working code example which implements the Affine coupling layer as defined in the `glow` paper with the code to compute its log determinant.

```Python
import torch
import torch.nn as nn
import memcnn
from memcnn.models.affine import AffineAdapterSigmoid


# define data attributes and generate some test input data X
batchsize = 2
channels = 5
w, h = 8, 8
X = torch.rand(batchsize, channels * 2, w, h)

# Create the invertible affine coupling layer from Table 1 from the GLow paper using the ReversibleBlock.
# This can be done by passing an arbitrary complex NN to the Fm attribute and passing
# an identity function to the Gm attribute.
#
# Note that NN here is arbitrary and can be swapped out for other operations as well.
# The AffineAdapterSigmoid is a helper class (nn.Module) which takes a function f and
# partitions the output h of f(x) = h into s and t by extracting every odd and even channel
# and subsequently outputs sigmoid(s), t
NN = AffineAdapterSigmoid(nn.Conv2d(in_channels=channels, out_channels=channels * 2,
                                    kernel_size=(1, 1), padding=0))

class IdentityModule(nn.Module):
    def forward(self, x):
        return torch.ones_like(x), torch.zeros_like(x)

glow_affine_layer = memcnn.ReversibleBlock(Fm=NN, Gm=IdentityModule(), coupling='affine',
                                          keep_input=True, keep_input_inverse=True)

# Given the glow_affine_layer we can now compute the log determinant given input X as follows:
# Note that in our implementation we directly output s and not log_s.
x_a, x_b = torch.chunk(X, 2, dim=1)
s, _ = glow_affine_layer.rev_block.Fm(x_b)
log_det = torch.sum(torch.log(torch.abs(s)))
print(log_det)


# ===== From this point on there are only some tests to validate things =====

# Validate invertibility of the glow_affine_layer
Y = glow_affine_layer(X)
X2 = glow_affine_layer.inverse(Y)
assert torch.allclose(X, X2, atol=1e-06)

# Validate that the IdentityModule() truly generates the identity trough the affine coupling
reversible_block_test = memcnn.ReversibleBlock(Fm=IdentityModule(), Gm=IdentityModule(), coupling='affine',
                                               keep_input=True)
X = torch.rand(batchsize, channels * 2, w, h)
Y = reversible_block_test(X)
assert torch.equal(X, Y)


```

**Comment by axium** [comment]
Thank you all. This has been really helpful.
