### ISSUE TITLE
Difference between implementations

### ISSUE THREAD

**Issue by thanasisfitsios** [silvandeleemput/memcnn#4]
Hello,
I noticed that in the revop.py file there are two different implementations ReversibleBlockFunction and ReversibleBlockFunction2. 
Are there any important differences between the two and reasons to choose one over the other?

**Comment by silvandeleemput** [comment]
Hi,

The implementations are very similar yet they derive approximately the same result (gradients for the weights during backward pass) in slightly different ways. 

The ReversibleBlockFunction computes the gradient on the backward pass by rebuilding the graph below and computing the gradients for: x, the weights of Fm, and the weights of Gm. It computes this in one go by passing the output gradients to the output y.
```
{x1, x2} = x
y1 = x1 + Fm(x2)
y2 = x2 + Gm(y1)
y = {y1, y2}
```

The ReversibleBlockFunction2 (currently the default implementation) also rebuilds the graph and computes the as gradients for: x, the weights of Fm, and the weights of Gm, but does this in two steps: first it computing the gradient for the weights of Gm and subsequently it computes the rest. This is more in line with the work of [Gomez et al. 2017](https://arxiv.org/abs/1707.04585). 

The differences on the actual gradients are small and yield approximately similar results for both implementations (also see the [revop unittests](https://github.com/silvandeleemput/memcnn/blob/master/memcnn/models/tests/test_revop.py)). With some initial runs I found that the ReversibleBlockFunction2 might be a bit faster to compute (hence it became the default) and the ReversibleBlockFunction might be a bit more accurate and might yield slightly better performance (albeit by a very small margin). However, this still needs proper bench-marks and validation.

I hope this post answers your questions.

**Comment by thanasisfitsios** [comment]
Thank you for the detailed answer, it is much clearer to me now.
