### ISSUE TITLE
Chaining ReversibleBlock modules

### ISSUE THREAD

**Issue by tychovdo** [silvandeleemput/memcnn#6]
Correct me if I'm wrong.
I am stacking multiple ReversibleBlock modules in a sequential manner (for instance wrapped in a nn.Sequential module). In this case, we only need to store the output activations of the last reversible block in the sequence to perform backpropagation (since we can calculate the input activations of a block using its output activations which are the input activations of the other block). Therefore, memory usage should be constant with network depth (in this case: depth=number stacked ReversibleBlocks).

However, it seems that when I stack ReversibleBlocks my GPU memory usage is still increasing with network depth.

Any idea what could go wrong here?

**Comment by tychovdo** [comment]
Nevermind. Sorry. The implementation seems to properly free memory, so I guess I am measuring an increase in memory usage due to the increase in model parameters.

**Comment by silvandeleemput** [comment]
Ok, no problem! I'll close this issue now.
